In [39]:
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
import urllib2
import csv
import pandas as pd
import os
import time
from selenium.common.exceptions import NoSuchElementException
from selenium.webdriver.common.by import By 
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

START_PAGE = 6
END_PAGE = 10
driver = webdriver.Firefox()
df = pd.DataFrame.from_csv('Stock code.csv', index_col=None)
df['Hong Kong offering shares'] = 0

def build_url(stock_code):
    stock_code = build_stock_code(stock_code)
    url = "http://hkf10.eastmoney.com/html_HKStock/index.html?securitycode=" + str(stock_code) + "&name=ipoInfo"
    return url

def build_stock_code(stock_code):
    s_stock_code = str(stock_code)
    if len(s_stock_code) == 3:
        return '00' + s_stock_code
    if len(s_stock_code) == 4:
        return '0' + s_stock_code
    
def build_currency(source):
    return source[-3:]

def main():    
    for i in range(len(df)):
        driver.get(build_url(df.loc[i, 'Stock Code']))
        time.sleep(5)
        #global_offering_shares = driver.find_element_by_xpath('//*[@id="table_stockIntro"]/tbody/tr[7]/td[2]').text
        hk_offering_shares     = driver.find_element_by_xpath('//*[@id="table_stockIntro"]/tbody/tr[31]/td[2]').text
        #currency = build_currency(driver.find_element_by_xpath('//*[@id="table_stockIntro"]/tbody/tr[25]/td[2]').text)
        #high_bound = driver.find_element_by_xpath('//*[@id="table_stockIntro"]/tbody/tr[23]/td[2]').text
        #low_bound              = driver.find_element_by_xpath('//*[@id="table_stockIntro"]/tbody/tr[24]/td[2]').text
        #final_offer_price      = driver.find_element_by_xpath('//*[@id="table_stockIntro"]/tbody/tr[5]/td[2]').text
        
        #df.loc[i, 'Global offering shares'] = global_offering_shares
        df.loc[i, 'Hong Kong offering shares'] = hk_offering_shares
        #df.loc[i, 'Currency'] = currency
        #df.loc[i, 'High Bound'] = high_bound
        #df.loc[i, 'Low Bound'] = low_bound
        #df.loc[i, 'Final offer price'] = final_offer_price
        
        driver.close()
if __name__ == "__main__":
    main()

NoSuchElementException: Message: Unable to locate element: //*[@id="table_stockIntro"]/tbody/tr[31]/td[2]

In [38]:
df

    Stock Code Hong Kong offering shares
0          565                21,875,000
1          568                         -
2          569                80,000,000
3          572                         0
4          573                         0
5          574                         0
6          579                         0
7          580                         0
8          581                         0
9          582                         0
10         658                         0
11         672                         0
12         691                         0
13         699                         0
14         700                         0
15         702                         0
16         703                         0
17         705                         0
18         707                         0
19         708                         0
20         712                         0
21         717                         0
22         728                         0
23         737                         0
24         750                         0
25         753                         0
26         756                         0
27         757                         0
28         763                         0
29         766                         0
..         ...                       ...
70        8089                         0
71        8092                         0
72        8095                         0
73        8100                         0
74        8103                         0
75        8106                         0
76        8108                         0
77        8109                         0
78        8111                         0
79        8225                         0
80        8226                         0
81        8227                         0
82        8228                         0
83        8233                         0
84        8235                         0
85        8236                         0
86        8239                         0
87        8243                         0
88        8247                         0
89        8249                         0
90        8250                         0
91        8256                         0
92        8258                         0
93        8266                         0
94        8270                         0
95        8271                         0
96        8273                         0
97        2663                         0
98        6080                         0
99        8470                         0

[100 rows x 2 columns]

In [25]:
df

    Stock Code
0          565
1          568
2          569
3          572
4          573
5          574
6          579
7          580
8          581
9          582
10         658
11         672
12         691
13         699
14         700
15         702
16         703
17         705
18         707
19         708
20         712
21         717
22         728
23         737
24         750
25         753
26         756
27         757
28         763
29         766
..         ...
70        8089
71        8092
72        8095
73        8100
74        8103
75        8106
76        8108
77        8109
78        8111
79        8225
80        8226
81        8227
82        8228
83        8233
84        8235
85        8236
86        8239
87        8243
88        8247
89        8249
90        8250
91        8256
92        8258
93        8266
94        8270
95        8271
96        8273
97        2663
98        6080
99        8470

[100 rows x 1 columns]