In [8]:
import csv
import pandas as pd
import os
import time

from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.common.exceptions import NoSuchElementException
from selenium.common.exceptions import TimeoutException
from selenium.common.exceptions import StaleElementReferenceException
from selenium.webdriver.common.by import By 
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

############################################################################################
#Initial variables
#This part of the code is used to set the inital parameters for the web crawler
############################################################################################
START_PAGE = 1
END_PAGE = 1
PROJECT_ABBR = "hkta"
PROJECT_NAME = "Project 5"
URL = "https://www.hkta.edu.hk/"

#Main window
driver =webdriver.Firefox(executable_path=r'D:\git\FINA2390-Programs\geckodriver.exe')
driver.get(URL)

df_columns = ['Date',
              'Year of Study',
              'Subject',
              'Sex',
              'Location',
              'Time',
              'Salary',
              'Remarks']


df_etf = pd.DataFrame(columns=df_columns)


def save_file(state, CURRENT_PAGE):
    if state == 'backup':
        filename = '['+ PROJECT_ABBR +'][Intrim Backup][' + str(CURRENT_PAGE) + ']' + PROJECT_NAME + ' PAGE ' + str(START_PAGE) + ' to PAGE ' + str(CURRENT_PAGE) + ' Records.csv'
        df_etf.to_csv(filename, index=False,  encoding='utf_8_sig')
        print '[Intrim Backup]Saved First '+ str(CURRENT_PAGE) + 'Pages Records to CSV'
    elif state == 'all':
        filename = '['+ PROJECT_ABBR +']'+ PROJECT_NAME +' PAGE ' + str(START_PAGE) + 'to PAGE ' + str(END_PAGE) + 'Records.csv'
        df_etf.to_csv(filename, index=False, encoding='utf_8_sig')
        print 'Exported to csv'
        
                                                

############################################################################################
#Main
#This part is the main function of the program
############################################################################################
def main():
    time.sleep(2)
    
    go_to_page(START_PAGE)
    time.sleep(1)
    print 'Start at PAGE'+ str(START_PAGE)
    
    n = 1
    for CURRENT_PAGE in range(START_PAGE,END_PAGE+1):
        print '--------------------PAGE ' + str(CURRENT_PAGE) +' START--------------------'
        START_TIMESTAMP = time.time()
        
        
        for row in driver.find_elements_by_xpath('//*[@id="menu-canvas"]/div/div/div/div/div/div[1]/div[3]/div[1]/div'):
            df_etf.loc[n, 'Location']         = row.find_element_by_xpath('a/div/ul/li[4]').text.split(u'：')[1]
            #df_etf.loc[n, 'Date']             = row.find_element_by_xpath('span[4]/span').text.split('-')[0]
            df_etf.loc[n, 'Sex']              = row.find_element_by_xpath('a/div/ul/li[2]').text.split(u'：')[1]
            df_etf.loc[n, 'Time']             = row.find_element_by_xpath('a/div/ul/li[3]').text.split(u'：')[1]
            df_etf.loc[n, 'Salary']           = row.find_element_by_xpath('a/div/ul/li[5]').text.split(u'：')[1]
            
            if(len(row.find_element_by_xpath('a/div/ul/li[6]').text.split(u'：')[1])!= 0):
                df_etf.loc[n, 'Remarks']     = row.find_element_by_xpath('a/div/ul/li[6]').text.split(u'：')[1]
            
            sub_yof = row.find_element_by_xpath('a/div/ul/li[1]').text.split(',')
            df_etf.loc[n, 'Year of Study']   = sub_yof[0]
            df_etf.loc[n, 'Subject']         = sub_yof[1]
            
            print '--------------------ROW ' + str(n) +' FINISHED--------------------'
            n = n + 1
            
        print '--------------------PAGE ' + str(CURRENT_PAGE) +' FINISH--------------------'
        END_TIMESTAMP = time.time()
        print '-TIME USED:' + str(START_TIMESTAMP-END_TIMESTAMP) + '-'
        
        #store every first 5,10,15... pages to CSV for backup purpose
        if(CURRENT_PAGE % 5) == 0:
            save_file('backup', CURRENT_PAGE)
        
    #set Source as QS for every row as this is crawl from QS
    
    #export the file to CSV
    save_file('all', CURRENT_PAGE)
    
    #close the driver
    driver.quit()
    
if __name__ == "__main__":
    main()

Start at PAGE1
--------------------PAGE 1 START--------------------
--------------------ROW 1 FINISHED--------------------
--------------------ROW 2 FINISHED--------------------
--------------------ROW 3 FINISHED--------------------
--------------------ROW 4 FINISHED--------------------
--------------------ROW 5 FINISHED--------------------
--------------------ROW 6 FINISHED--------------------
--------------------ROW 7 FINISHED--------------------
--------------------ROW 8 FINISHED--------------------
--------------------ROW 9 FINISHED--------------------
--------------------ROW 10 FINISHED--------------------
--------------------ROW 11 FINISHED--------------------
--------------------ROW 12 FINISHED--------------------
--------------------ROW 13 FINISHED--------------------
--------------------ROW 14 FINISHED--------------------
--------------------ROW 15 FINISHED--------------------
--------------------ROW 16 FINISHED--------------------
--------------------ROW 17 FINISHED--------------------
--------------------ROW 18 FINISHED--------------------
--------------------ROW 19 FINISHED--------------------
--------------------ROW 20 FINISHED--------------------
--------------------ROW 21 FINISHED--------------------
--------------------ROW 22 FINISHED--------------------
--------------------ROW 23 FINISHED--------------------
--------------------ROW 24 FINISHED--------------------
--------------------ROW 25 FINISHED--------------------
--------------------ROW 26 FINISHED--------------------
--------------------ROW 27 FINISHED--------------------
--------------------ROW 28 FINISHED--------------------
--------------------ROW 29 FINISHED--------------------
--------------------ROW 30 FINISHED--------------------
--------------------ROW 31 FINISHED--------------------
--------------------ROW 32 FINISHED--------------------
--------------------ROW 33 FINISHED--------------------
--------------------ROW 34 FINISHED--------------------
--------------------ROW 35 FINISHED--------------------
--------------------ROW 36 FINISHED--------------------
--------------------ROW 37 FINISHED--------------------
--------------------ROW 38 FINISHED--------------------
--------------------ROW 39 FINISHED--------------------
--------------------ROW 40 FINISHED--------------------
--------------------PAGE 1 FINISH--------------------
-TIME USED:-2.87000012398-
Exported to csv

In [9]:
df_etf

,Date,Year of Study,Subject,Sex,Location,Time,Salary,Remarks
1,NaN,中四,數學,女-1名,仁安大廈(廣華醫院附近),1.5hr,$160/1hr,NaN
2,NaN,中四,繪畫,女-1名,仁安大廈(廣華醫院附近),2hr,$250/1hr,NaN
3,NaN,中四,數學(M2),女-1名,洞梓路,1hr,$180/1hr,大學程度 11:00
4,NaN,小三,全科,男-1名,大隴街怡勝花園,1.5hr,$110/1hr,大學程度 一二四 16:30後
5,NaN,中四,敲擊樂,女-1名,柏景灣,1hr,$300/1hr,五級 女導師
6,NaN,小四,奧數,男-1名,黃竹坑深灣3號南濤閣,2hr,$180/1hr,大學畢業 星期六/日 19:00-21:00
7,NaN,成人(初級),意大利語,女-1名,香港大學站,1.5hr,$200/1hr,大學程度 上午/下午
8,NaN,小四,全科,女-1名,穗禾苑,2hr,$120/1hr,大學程度 女導師 一 18:00 二五 16:00
9,NaN,成人(大學一年級),數學,男-1名,地鐵站附近,2hr,$350/1hr,NaN
10,NaN,HighDip,生物心理學,女-1名,荃灣花園,1.5hr,$280/1hr,大學畢業 下午/晚上
11,NaN,小二(初學),敲擊樂(木琴,女-1名,曼克頓山,1hr,$220/1hr,演奏級 一/六 1800-1845 日 1100
12,NaN,小四,全科,男-1名,大尾督龍尾,1.5hr,$100/1hr,大學程度 二 三 四 19:30/20:00
13,NaN,中一,中文,男-1名,西營盤,1.5hr,$150/1hr,大學程度 女導師 二 / 四 1630
14,NaN,小六,中一,女-2名,駿景園,2hr,$200/1hr,大學畢業 女導師 六 上午/15:00-17:00
15,NaN,中五,地理,男-1名,九龍仔秀竹園道,2hr,$300/1hr,全職補習 六 14:00-16:00
16,NaN,小五,全科,女-1名,嘉亨灣,1.5hr,$180/1hr,全職補習 女導師 一至四 17:00/1730
17,NaN,小一,中文,男-1名,馬頭圍,1.5hr,$90/1hr,中七程度 女導師 一二三五 16:00-19
18,NaN,5歲,全科,男-1名,維景灣畔,2hr,$80/1hr,中五程度 一至五/17:00 要到北角
19,NaN,中五,中文,女-1名,明珠華軒,1.5hr,$150/1hr,大學程度 女導師 六
20,NaN,小二,全科,男-1名,黃大仙上村,1hr,$90/1hr,大學程度 女導師 二 5:00/6:00 一 四 6:00-7:00
21,NaN,小二,全科,男-1名,藍田村,1.5hr,$80/1hr,中七程度 男導師 一至三 18:30/19:00 四 1900
22,NaN,小二,全科,男-1名,美景花園,1.5hr,$100/1hr,大學程度 五 1630-1800
23,NaN,小四,英文,女-1名,葵馥苑安葵閣,1.5hr,$120/1hr,大學程度 女導師 一至四 1730/1800
24,NaN,小六,中四,女-2名,則魚涌,2hr,$150/1hr,中七程度 女導師 五 18:00 日 14:00-16:00
25,NaN,小三,英文,男-1名,朗庭園,1.5hr,$120/1hr,大學程度 女導師 五 16:00後 六 15:00後
26,NaN,YEAR 10,英文 / 理科,女-1名,九龍塘多實街8號,1.5hr,$250/1hr,全職補習 女導師 一至四 17:00
27,NaN,九級,二胡,男-1名,長青村,1.5hr,$350/1hr,八級 星期日 15:00後
28,NaN,中四,通識教育,男-1名,新都城,1.5hr,$320/1hr,現職教師 五/日
29,NaN,中一,全科,女-1名,美城苑,1.5hr,$110/1hr,大學程度 女導師 17:00/18:00
30,NaN,成人,社會科學,女-1名,駿景園,3hr,$200/1hr,全職補習 女導師 SAT OR SUN 2:30-5:30PM
31,NaN,小三,中文,女-2名,湖光街3號,1hr,$180/1hr,NaN
32,NaN,小一,全科,女-1名,東頭湾道,1.5hr,$100/1hr,一至四/約1630-1700開始
33,NaN,4歲,珠心算,女-1名,香港海逸豪園,1hr,$180 /1hr,現職教師
34,NaN,小一,中文,女-1名,日出康城,1hr,$100/1hr,中七程度 女導師 一至五/1700-1730開始
35,NaN,小五,全科,男-1名,翠屏邨,1.5hr,$100-250 /1hr,"現職教師 女導師 星期五,日PM5:00後"
36,NaN,中四,數學,女-1名,翠竹花園,2hr,$140/1hr,大學程度 女導師 四 19:30-21:30
37,NaN,小五,英文,男-1名,翠竹花園,1.5hr,$200/1hr,全職補習 女導師 一二四 4:30
38,NaN,小四,全科,男-1名,昌運中心,1hr,$100/1hr,大學程度 女導師 二 四 1800-1900
39,NaN,小五,全科,女-1名,利東邨,1.5hr,$120/1hr,大學程度 女導師 二18:00 三四 17:00 (19:30前)
40,NaN,中一,中文,女-1名,銀禧花園,1.5hr,$300/1hr,現職教師 六 1730 / 日 1400/1500後